# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/jisuanjizuchengyuanli/vivado2.2/lab6/Cpu_painting/lab/lab.srcs/sources_1/ip/instrcution_memory/instrcution_memory.xci
# IP: The module: 'instrcution_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/jisuanjizuchengyuanli/vivado2.2/lab6/Cpu_painting/lab/lab.srcs/sources_1/ip/instrcution_memory/instrcution_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instrcution_memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/jisuanjizuchengyuanli/vivado2.2/lab6/Cpu_painting/lab/lab.srcs/sources_1/ip/instrcution_memory/instrcution_memory.xci
# IP: The module: 'instrcution_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/jisuanjizuchengyuanli/vivado2.2/lab6/Cpu_painting/lab/lab.srcs/sources_1/ip/instrcution_memory/instrcution_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instrcution_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
