# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/jisuanjizuchengyuanli/vivado2.2/lab6/Cpu_painting/lab/lab.srcs/sources_1/ip/VRAM/VRAM.xci
# IP: The module: 'VRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/jisuanjizuchengyuanli/vivado2.2/lab6/Cpu_painting/lab/lab.srcs/sources_1/ip/VRAM/VRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/jisuanjizuchengyuanli/vivado2.2/lab6/Cpu_painting/lab/lab.srcs/sources_1/ip/VRAM/VRAM.xci
# IP: The module: 'VRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/jisuanjizuchengyuanli/vivado2.2/lab6/Cpu_painting/lab/lab.srcs/sources_1/ip/VRAM/VRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
